recipe_app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('recipes.urls')),
   path('recipes/', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import welcome, recipe_list, recipe_detail, user_login, user_logout, recipe_search, add_recipe



app_name = 'recipes'

urlpatterns = [
   path('', welcome, name='welcome'),
   path('recipes/', recipe_list, name='recipe_list'),
   path('recipes/<int:recipe_id>/', recipe_detail, name='recipe_detail'),
   path('login/', user_login, name='user_login'),
   path('logout/', user_logout, name='user_logout'),
   path('recipes/search/', recipe_search, name='recipe_search'),
   path('recipes/add/', add_recipe, name='add_recipe'),
]

recipes/models.py
from django.db import models



class Recipe(models.Model):
   recipe_name = models.CharField(max_length=255)
   ingredients = models.TextField()
   cooking_time = models.IntegerField()
   difficulty_rating = models.CharField(max_length=50, blank=True, null=True)
   description_details = models.TextField()
   image = models.ImageField(upload_to='recipe_images/', default='No_image_available.jpg', blank=True, null=True)

   def __str__(self):
      return self.recipe_name
   
   def calculate_difficulty(self):
      if self.cooking_time < 10 and len(self.ingredients.split(',')) < 5:
         self.difficulty_rating = 'Easy'
      elif self.cooking_time < 10 and len(self.ingredients.split(',')) >= 5:
         self.difficulty_rating = 'Medium'
      elif self.cooking_time >= 10 and len(self.ingredients.split(',')) < 5:
         self.difficulty_rating = 'Intermediate'
      else:
         self.difficulty_rating = 'Hard'

   def save(self, *args, **kwargs):
      self.calculate_difficulty()
      super().save(*args, **kwargs)

recipes/forms.py
from django import forms
from .models import Recipe


class RecipeSearchForm(forms.Form):
   ingredients = forms.CharField(
      label='Ingredients',
      required=False
   )
   show_all = forms.BooleanField(
      label='Show All',
      required=False,
      initial=False
   )

class AddRecipeForm(forms.ModelForm):
   class Meta:
      model = Recipe
      fields = ['recipe_name', 'ingredients', 'cooking_time', 'description_details', 'image']

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q
from .models import Recipe
from .forms import RecipeSearchForm, AddRecipeForm

from django.http import JsonResponse
import pandas as pd
from django.core.serializers import serialize

import matplotlib.pyplot as plt
from io import BytesIO
import base64 
import matplotlib
matplotlib.use('agg')



def welcome(request):
   recipes = Recipe.objects.all() 
   return render(request, 'recipes/recipes_home.html', {'recipes': recipes}) 

@login_required
def recipe_detail(request, recipe_id):
   if request.user.is_authenticated:
      recipe = get_object_or_404(Recipe, pk=recipe_id)
      return render(request, 'recipes/recipe_details.html', {'recipe': recipe})
   else:
      return redirect('recipes:user_login')

def user_login(request):
   if request.method == 'POST':
      username = request.POST.get('username')
      password = request.POST.get('password')
      user = authenticate(request, username=username, password=password)
      if user:
         login(request, user)
         return redirect('recipes:recipe_list') 
      else:
         messages.error(request, "Invalid username or password. Please try again.")
   return render(request, 'recipes/user_login.html')

def user_logout(request):
   logout(request)
   messages.success(request, "You've successfully logged out.")
   return render(
      request, 
      'recipes/success.html', 
      {'message': "You've successfully logged out."})

def recipe_search(request):
   form = RecipeSearchForm(request.GET)
   recipes = Recipe.objects.all()

   if form.is_valid():
      ingredients = form.cleaned_data.get('ingredients')
      if ingredients:
         recipes = recipes.filter(
            Q(ingredients__icontains=ingredients)
         )

   bar_chart_img_base64, pie_chart_img_base64, line_chart_img_base64 = generate_charts_data(recipes)

   return render(
      request, 
      'recipes/search_results.html', 
      {
         'search_results': recipes, 
         'form': form,
         'bar_chart_img': bar_chart_img_base64,
         'pie_chart_img': pie_chart_img_base64,
         'line_chart_img': line_chart_img_base64,
      }
   )


def generate_charts_data(recipes):
   data = {
      'Recipe Name': [recipe.recipe_name for recipe in recipes],
      'Cooking Time': [recipe.cooking_time for recipe in recipes],
   }
   df = pd.DataFrame(data)

   bar_chart_img_base64, pie_chart_img_base64, line_chart_img_base64 = generate_charts(df)

   return bar_chart_img_base64, pie_chart_img_base64, line_chart_img_base64

def generate_charts(df):
   plt.switch_backend('agg')

   # Data
   recipe_names = df['Recipe Name']
   cooking_times = df['Cooking Time']

   # Bar Chart
   plt.figure(figsize=(10, 6))
   plt.bar(recipe_names, cooking_times, color='blue')
   plt.xlabel('Recipe Names')
   plt.ylabel('Cooking Time (minutes)')
   plt.title('Cooking Time Comparison for Recipes')
   plt.xticks(rotation=45, ha='right')
   bar_chart_img = BytesIO()
   plt.savefig(bar_chart_img, format='png')
   plt.close()

   # Pie Chart
   plt.figure(figsize=(8, 8))
   plt.pie(cooking_times, labels=recipe_names, autopct='%1.1f%%', startangle=140)
   plt.axis('equal')
   plt.title('Percentage of Cooking Time for Each Recipe')
   pie_chart_img = BytesIO()
   plt.savefig(pie_chart_img, format='png')
   plt.close()

   # Line Chart
   plt.figure(figsize=(10, 6))
   plt.plot(recipe_names, cooking_times, marker='o', color='green', linestyle='-', linewidth=2, markersize=8)
   plt.xlabel('Recipe Names')
   plt.ylabel('Cooking Time (minutes)')
   plt.title('Trends in Cooking Time Across Recipes')
   plt.xticks(rotation=45, ha='right')
   line_chart_img = BytesIO()
   plt.savefig(line_chart_img, format='png')
   plt.close()

   # Convert images
   bar_chart_img_base64 = base64.b64encode(bar_chart_img.getvalue()).decode('utf-8')
   pie_chart_img_base64 = base64.b64encode(pie_chart_img.getvalue()).decode('utf-8')
   line_chart_img_base64 = base64.b64encode(line_chart_img.getvalue()).decode('utf-8')

   return bar_chart_img_base64, pie_chart_img_base64, line_chart_img_base64

@login_required
def add_recipe(request):
   if request.method == 'POST':
      form = AddRecipeForm(request.POST, request.FILES)
      if form.is_valid():
         form.save()
         messages.success(request, "Recipe added successfully!")
         return redirect('recipes:recipe_list')
      else:
         messages.error(request, "Error adding the recipe. Please check the form.")
   else:
      form = AddRecipeForm()

   return render(request, 'recipes/add_recipe.html', {'form': form})

@login_required
def recipe_list(request):
   if request.user.is_authenticated:
      form = RecipeSearchForm(request.GET)
      recipes = Recipe.objects.all()

      if form.is_valid():
         search_query = form.cleaned_data.get('ingredients')
         show_all = form.cleaned_data.get('show_all')

         if show_all:
            recipes = Recipe.objects.all()
         elif search_query:
            recipes = Recipe.objects.filter(
               Q(ingredients__icontains=search_query) | Q(recipe_name__icontains=search_query)
            )

         # Generate charts
         bar_chart_img_base64, pie_chart_img_base64, line_chart_img_base64 = generate_charts_data(recipes)

         # Render
         return render(
            request,
            'recipes/recipe_list.html',
            {
               'recipes': recipes,
               'bar_chart_img': bar_chart_img_base64,
               'pie_chart_img': pie_chart_img_base64,
               'line_chart_img': line_chart_img_base64,
               'form': form,
            }
         )

      bar_chart_img_base64, pie_chart_img_base64, line_chart_img_base64 = generate_charts_data(recipes)

      return render(
         request,
         'recipes/recipe_list.html',
         {
            'recipes': recipes,
            'bar_chart_img': bar_chart_img_base64,
            'pie_chart_img': pie_chart_img_base64,
            'line_chart_img': line_chart_img_base64,
            'form': form,
         }
      )
   else:
      return redirect('recipes:user_login')

recipes/templates/recipes/add_recipe.html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% load static %}
   <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
   <title>Add Recipe</title>
</head>

<body>

   <header>
      <h1>Add Recipe</h1>
   </header>

   <main>
      <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         <label for="id_recipe_name">Recipe Name:</label>
         {{ form.recipe_name }}
         <br>
         <label for="id_ingredients">Ingredients:</label>
         {{ form.ingredients }}
         <br>
         <label for="id_cooking_time">Cooking Time:</label>
         {{ form.cooking_time }}
         <br>
         <label for="id_description_details">Description Details:</label>
         {{ form.description_details }}
         <br>
         <label for="id_image">Image:</label>
         {{ form.image }}
         <br>
         <button class="login-button" type="submit">Add Recipe</button>
      </form>
   </main>

   <footer>
      <p>&copy; 2023 Siders & CareerFoundry Recipe App</p>
   </footer>

</body>

</html>

recipes/templates/recipes/recipe_details.html
<!DOCTYPE html>
<html lang="en">


   <head>

      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

      <title>{{ recipe.recipe_name }}</title>
   </head>

   <body>

      <header>
         <h1>{{ recipe.recipe_name }}</h1>

         <a class="logout-button" href="{% url 'recipes:user_logout' %}">Logout</a>
      </header>

      <main>
         <h3>{{ recipe.description_details }}</h3>
 
         <div class="recipe-details">
            <img 
               src="{{ recipe.image.url }}" 
               alt="{{ recipe.recipe_name }}" 
               style="max-width: 100%; max-height: 300px; object-fit: cover; border-radius: 8px; margin-bottom: 10px;"
            >

            <div class="recipe-details-section">
               <h2>Ingredients: </h2>
               <p>{{ recipe.ingredients }}</p>
            </div>
            <div class="recipe-details-section">
               <h2>Cooking Time: </h2>
               <p>{{ recipe.cooking_time }} minutes</p>
            </div>
            <div class="recipe-details-section">
               <h2>Difficulty: </h2>
               <p>{{ recipe.difficulty_rating }}</p>
            </div>
         </div>
      </main>

      <footer>
         <p>&copy; 2023 Siders & CareerFoundry Recipe App</p>
      </footer>

   </body>

</html>

recipes/templates/recipes/recipe_list.html
<!DOCTYPE html>
<html lang="en">


   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

      <title>Your Recipes</title>
   </head>

   <body>

      <header>
         <h1>Find Recipes</h1>

         <a class="logout-button" href="{% url 'recipes:user_logout' %}">Logout</a>
      </header>

      <main>
         <h3>Search and filter the available recipes by entering an ingredient:</h3>
     
         <form method="get" action="{% url 'recipes:recipe_list' %}">
            {{ form.ingredients }}
            <button class="login-button" type="submit">Search</button>
            <br> <br>
            <label for="{{ form.show_all.id_for_label }}">Show All</label>
            {{ form.show_all }}
         </form>
         <br>
         <a href="{% url 'recipes:add_recipe' %}" class="login-button">Add Recipe</a>
         <br>
         <p>Click any of your recipes for the full recipe description</p>
     
         {% if recipes %}
         <div class="displayed-recipes">
             {% for recipe in recipes %}
                 <div class="recipe-card">
                     <a href="{% url 'recipes:recipe_detail' recipe.id %}">
                         <img src="{{ recipe.image.url }}" alt="{{ recipe.recipe_name }}" width="200" height="150">
                         <p>{{ recipe.recipe_name }}</p>
                     </a>
                 </div>
             {% endfor %}
         </div>
         {% endif %}
         <br>
         <div class="charts">
             <img src="data:image/png;base64,{{ bar_chart_img }}" alt="Bar Chart">
             <img src="data:image/png;base64,{{ pie_chart_img }}" alt="Pie Chart">
             <img src="data:image/png;base64,{{ line_chart_img }}" alt="Line Chart">
         </div>
     
     </main>

      <footer>
         <p>&copy; 2023 Siders & CareerFoundry Recipe App</p>
      </footer>

   </body>

</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">


   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

      <title>My Recipe App</title>
   </head>

   <body>

      <header>
         <h1>Welcome to My Recipe App</h1>

      </header>

      

      <main>
         <h2>Explore and discover delicious recipes!</h2>

         <h3><a href="{% url 'recipes:user_login' %}" class="login-link">Log in</a> to go to your saved recipes</h3>
         
         <a class="login-button" href="{% url 'recipes:user_login' %}">Log In</a>
         <div>
            <br> <br>
            <p>Lorem Ipsum</p>
         </div>
      </main>

      <footer>
         <p>&copy; 2023 Siders & CareerFoundry Recipe App</p>
      </footer>

   </body>

</html>

recipes/templates/recipes/success.html
<!DOCTYPE html>
<html lang="en">

   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

      <title>Logout Success</title>
   </head>

   <body>
      <h2>{{ message }}</h2>
      <a href="{% url 'recipes:user_login' %}">Log back in</a>
   </body>

</html>

recipes/templates/recipes/user_login.html
<!DOCTYPE html>
<html lang="en">

   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

      <title>Login</title>
   </head>

   <body>
      <h2>Login</h2>

      <form method="post" action="{% url 'recipes:user_login' %}">
         {% csrf_token %}
         <label for="username">Username:</label>
         <input type="text" name="username" required>
         <br>
         <label for="password">Password:</label>
         <input type="password" name="password" required>
         <br>
         <button class="login-button" type="submit">Log In</button>
      </form>

   </body>

</html>